# copied from https://jupyterbook.org/publish/gh-pages.html?highlight=github%20pages

name: deploy-web

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r .github/workflows/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./web/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/_build/html
        publish_branch: gh-pages

